### PR TITLE
[FEATURE] Encode the request body with unicode (very simply) and support UTF-8 charset in hoverfly file

### PR DESCRIPTION
**Pull request by lucwarrot**
Hello @Lemick 

First of all, thank you for your really cool plugin 🙂 

I propose a very simply implementation of my needs.
I have to encode some HTML in JSON in my request bodies and i simply replace '<' and '>' by their unicode.

I suggest you to use Monaco in request body matcher if it's JSON.

And last but not least, I tried to support UTF8 in the Intellij Plugin.

### CODE REVIEW

**Comment by Lemick** [comment]
Hi Luc thank for the idea :D

I will take a look and try to test it once I have a little time (I've no automated test on the plugin part)

**Comment by Lemick** [comment]
@lucwarrot Just curious, why encoding  with Unicode chars rather than HTML entities ?
Since HTML tags remains "valid" JSON strings i'm wondering if there are legit use cases for people to not want these characters to be encoded 🤔

**Comment by lucwarrot** [comment]
I think, you are right, my use case is very specific.

I give you what I need.

If i want to match a request with the given body

```json
{
  "test":"<div>hello</div>"
}
```

In my hoverfly file, i need to have something like this:

```json
{
  "matcher": "json"
  "value": "{\"test\":\"\\u003cdiv\\u003ehello\\u003c/div\\u003e\"}"
}
```

**Comment by Lemick** [comment]
I needed to recreate a [PR](https://github.com/Lemick/hoverfly-ui/pull/33) to add a commit, i just:
- Fixed the E2E test
- Used another function for decoding that seems to [perform better](https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiItTjR0cXQyVVh0VUNQcldiOXl3a1UiLCJjb2RlIjoiZnVuY3Rpb24gYjY0RGVjb2RlVW5pY29kZSh2YWx1ZSkge1xuICByZXR1cm4gZGVjb2RlVVJJQ29tcG9uZW50KEFycmF5LnByb3RvdHlwZS5tYXAuY2FsbChhdG9iKHZhbHVlKSwgZnVuY3Rpb24oYykge1xuICAgICAgcmV0dXJuICclJyArICgnMDAnICsgYy5jaGFyQ29kZUF0KDApLnRvU3RyaW5nKDE2KSkuc2xpY2UoLTIpXG4gIH0pLmpvaW4oJycpKVxufVxuXG5iNjREZWNvZGVVbmljb2RlKERBVEEpIiwibmFtZSI6ImI2NERlY29kZVVuaWNvZGUiLCJkZXBlbmRlbmNpZXMiOltdfSx7ImlkIjoiYk1aQnMwOEp6dDdsWnpoY0lFNzg0IiwiY29kZSI6ImZ1bmN0aW9uIGRlY29kZUJhc2U2NFV0ZjgoYmFzZTY0KSB7XG4gIGNvbnN0IHRleHQgPSBhdG9iKGJhc2U2NCk7XG4gIGNvbnN0IGxlbmd0aCA9IHRleHQubGVuZ3RoO1xuICBjb25zdCBieXRlcyA9IG5ldyBVaW50OEFycmF5KGxlbmd0aCk7XG4gIGZvciAobGV0IGkgPSAwOyBpIDwgbGVuZ3RoOyBpKyspIHtcbiAgICBieXRlc1tpXSA9IHRleHQuY2hhckNvZGVBdChpKTtcbiAgfVxuICBjb25zdCBkZWNvZGVyID0gbmV3IFRleHREZWNvZGVyKCk7XG4gIHJldHVybiBkZWNvZGVyLmRlY29kZShieXRlcyk7XG59XG5cbmRlY29kZUJhc2U2NFV0ZjgoREFUQSkiLCJuYW1lIjoiZGVjb2RlQmFzZTY0VXRmOCIsImRlcGVuZGVuY2llcyI6W119XSwiY29uZmlnIjp7Im5hbWUiOiJCYXNpYyBleGFtcGxlIiwicGFyYWxsZWwiOnRydWUsImdsb2JhbFRlc3RDb25maWciOnsiZGVwZW5kZW5jaWVzIjpbXX0sImRhdGFDb2RlIjoicmV0dXJuIFwiZXlKclpYa3dJam9pZG1Gc2RXVXdJaXdpYTJWNU1TSTZJblpoYkhWbE1TSXNJbXRsZVRJaU9pSjJZV3gxWlRJaUxDSnJaWGt6SWpvaWRtRnNkV1V6SWl3aWEyVjVOQ0k2SW5aaGJIVmxOQ0lzSW10bGVUXCIifX0)
- Removed the encoding in the matcher, if you are okay to better do it on your side ? Because we can't be sure that all users want this encoding, or even use another encoding (like Unicode everywhere or HTML entities..)

Is it acceptable to you ?

**Comment by lucwarrot** [comment]
Yes, it looks good to me.
I will think about the encoding side and propose a better way 👍

**Comment by Lemick** [comment]
Nice, thanks 👍

**Pull request closed without merging**
